#!/usr/bin/python

# -------------------------------------------------------------------------- #
# Copyright 2016-2018                                                        #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

import lxd_common as lc
client = lc.Client()

DOMAIN = lc.sys.argv[1]
NIC_MAC = lc.sys.argv[2]
NIC_BRIDGE = lc.sys.argv[3]
NIC_MODEL = lc.sys.argv[4]
NET_DRV = lc.sys.argv[5]
NIC_TARGET = lc.sys.argv[6]
# UNKNOWN = lc.sys.argv[7]
HOST_IP = lc.sys.argv[8]

lc.log_function(lc.separator)

container = client.containers.get(DOMAIN)

name = 'eth%s' % (NIC_TARGET.split('-')[-1])
vm_nic = lc.map_nic(name, NIC_BRIDGE, NIC_MAC, NIC_TARGET)
container.devices.update(vm_nic)
container.save(wait=True)

exit()
