#!/usr/bin/python

# -------------------------------------------------------------------------- #
# Copyright 2016-2018                                                        #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

import lxd_common as lc
client = lc.Client()

DOMAIN = lc.sys.argv[1]
NIC_MAC = lc.sys.argv[2]
# UNKNOWN = lc.sys.argv[3]
HOST_IP = lc.sys.argv[4]

container = client.containers.get(DOMAIN)
lc.log_function(lc.separator)


def get_interface(devices, hwaddr):
    "Get interface name from hwaddr inside the container's devices dict"
    for k, v in devices.iteritems():
        if k.__contains__('eth') and v['hwaddr'] == hwaddr:
            return v['name']


iface = get_interface(container.devices, NIC_MAC)

del container.devices[iface]
container.save(wait=True)

exit()
