#!/usr/bin/python2

# -------------------------------------------------------------------------- #
# Copyright 2016-2018                                                        #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

import lxd_common as lc
t0 = lc.time()

DOMAIN = lc.sys.argv[1]  # Domain name: one-101
SOURCE = lc.sys.argv[2]  # Image path
TARGET = lc.sys.argv[3]  # Device in the guest: hda, sdc, vda, xvdc
TARGET_INDEX = lc.sys.argv[4]  # Position in the list of disks
VM_ID = lc.sys.argv[5]

client = lc.Client()
container = client.containers.get(DOMAIN)

lc.clock(t0)
lc.sys.exit(1)
