#!/usr/bin/python

import os
import lxd_common as lc
import lxd_unified_image as lui
import subprocess as sp
import re
from pylxd.exceptions import LXDAPIException

t0 = lc.time()
client = lc.Client()
VM_ID = lc.sys.argv[3]
VM_NAME = lc.sys.argv[1] 

container = client.containers.get(VM_NAME)

dicc = lc.xml_start(container.config.get('user.xml'))
DS_ID = dicc['/VM/HISTORY_RECORDS/HISTORY/DS_ID'][0]
DS_LOCATION = '/var/lib/one/datastores/' + DS_ID + '/' + VM_ID + '/'

lc.log_function('INFO', 'container: ' + VM_NAME + ' deleting')

# Container stop
try:
    if lc.sys.argv[-1] == 'force':
        # called from 'cancel'
        lc.log_function('INFO', 'container: ' + VM_NAME + ' force stop')
        container.stop(force=True, wait=True)
    else:
        container.stop(wait=True)
except LXDAPIException as lxdapie:
    if container.status == 'Stopped':
        lc.log_function('INFO', 'container: ' + VM_NAME + ' already stopped')
    else:
        lc.log_function('ERROR', lxdapie)
        lui.uniimg_container_wipe(client, container)
        lc.sys.exit(1)

fingerprint = container.config.get('volatile.base_image')

# Image publish and export
# FIXME: fix to use pylxd's image.export() method
try:
    """
    Publish the new iamge onto local LXD image store
    """
    new_fingerprint = None
    new_fingerprint = sp.check_output('lxc publish ' + VM_NAME, stderr=sp.STDOUT, shell=True)
    new_fingerprint = re.split('\s', new_fingerprint.rstrip())[-1]
    lc.log_function('INFO', 'image: published as ' + new_fingerprint)
except sp.CalledProcessError as cpe:
    lc.log_function('WARN', cpe)

try:
    """
    Export image onto OpenNebula datastore
    """
    if not new_fingerprint:
        # Assumes that 'lxc publish' failed because the image already exists.
        # Get image's fingerprint from stderr output.
        new_fingerprint = re.split('\s', cpe.output.rstrip())[-1]

    export_image = None
    export_image = sp.check_output('lxc image export ' + new_fingerprint + ' ' + DS_LOCATION, shell=True)
    export_image = re.split('\s', export_image.rstrip())[-1]
    lc.log_function('INFO', 'image: exported ' + export_image)
except sp.CalledProcessError as cpe:
    lc.log_function('WARN', cpe)

try:
    """
    Rename exported image to 'disk.0'
    """
    os.rename(export_image, DS_LOCATION + '/disk.0')
    lc.log_function('INFO', export_image + ' renamed to disk.0')
except OSError as ose:
    lc.log_function('WARN', ose)

try:
    """
    Clean up local LXD image store
    """
    image = client.images.get(new_fingerprint)
    image.delete()
except LXDAPIException as lxdapie:
    lc.log_function('WARN', lxdapie)

try:
    """
    Delete container
    """
    lui.uniimg_container_wipe(client, container)
    lc.log_function('INFO', 'container: ' + VM_NAME + ' deleted')
except LXDAPIException as lxdapie:
    lc.log_function('ERROR', lxdapie)
    raise

lc.clock(t0, VM_ID)
